import math
import warnings
from functools import partial
import torch
import torch.nn as nn
import numpy as np
from einops import rearrange, repeat

from model.base import Encoder


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def get_1d_sincos_pos_embed_from_grid(embed_dim, pos):
    """
    embed_dim: output dimension for each position
    pos: a list of positions to be encoded: size (M,)
    out: (M, D)
    """
    assert embed_dim % 2 == 0
    omega = np.arange(embed_dim // 2, dtype=np.float)
    omega /= embed_dim / 2.
    omega = 1. / 10000**omega  # (D/2,)

    pos = pos.reshape(-1)  # (M,)
    out = np.einsum('m,d->md', pos, omega)  # (M, D/2), outer product

    emb_sin = np.sin(out) # (M, D/2)
    emb_cos = np.cos(out) # (M, D/2)

    emb = np.concatenate([emb_sin, emb_cos], axis=1)  # (M, D)
    return emb


def get_2d_sincos_pos_embed_from_grid(embed_dim, grid):
    assert embed_dim % 2 == 0

    # use half of dimensions to encode grid_h
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (H*W, D/2)
    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (H*W, D/2)

    emb = np.concatenate([emb_h, emb_w], axis=1) # (H*W, D)
    return emb


def get_2d_sincos_pos_embed(embed_dim, grid_size, cls_token=False):
    """
    grid_size: int of the grid height and width
    return:
    pos_embed: [grid_size*grid_size, embed_dim] or [1+grid_size*grid_size, embed_dim] (w/ or w/o cls_token)
    """
    grid_h = np.arange(grid_size, dtype=np.float32)
    grid_w = np.arange(grid_size, dtype=np.float32)
    grid = np.meshgrid(grid_w, grid_h)  # here w goes first
    grid = np.stack(grid, axis=0)

    grid = grid.reshape([2, 1, grid_size, grid_size])
    pos_embed = get_2d_sincos_pos_embed_from_grid(embed_dim, grid)
    if cls_token:
        pos_embed = np.concatenate([np.zeros([1, embed_dim]), pos_embed], axis=0)
    return pos_embed


# class PatchEmbed(nn.Module):
#     """
#     BERT Embedding which is consisted with under features
#         1. TokenEmbedding : normal embedding matrix
#         2. PositionalEmbedding : adding positional information using sin, cos
#         2. ShapeEmbedding : adding path shape  info
#
#         sum of all these features are output of BERTEmbedding
#     """
#
#     def __init__(self, node2vec, time2vec, embed_dim=128, dropout=0.1):
#         """
#         :param vocab_size: total vocab size
#         :param embed_size: embedding size of token embedding
#         :param dropout: dropout rate
#         """
#         super().__init__()
#         self.token = nn.Embedding.from_pretrained(node2vec)
#         self.time = nn.Embedding.from_pretrained(time2vec)
#
#
#     def forward(self, seq, ts):#, seq_rt, seq_ow, seq_lane):
#         x = self.token(seq)
#         ts_ =self.time(ts)
#
#         return x, ts_  #self.norm(x) ####BNC where c =1


class PatchEmbed(nn.Module):
    def __init__(self, num_tokens, num_time_tokens, embed_dim):
        super(PatchEmbed, self).__init__()

        self.token_embedding = nn.Embedding(num_tokens, embed_dim)
        self.time_embedding = nn.Embedding(num_time_tokens, embed_dim)

    def forward(self, x, ts):
        x = self.token_embedding(x)
        ts = self.time_embedding(ts)
        return x, ts


class PositionEmbed(nn.Module):
    def __init__(self, num_patches=100, d_model=128, num_tokens=0):
        super().__init__()

        # Compute the positional encodings once in log space.
        self.num_tokens = num_tokens
        assert self.num_tokens >=0, "num_tokens must be class token or no, so must 0 or 1"
        pe = torch.zeros(num_patches+self.num_tokens, d_model).float()
        pe.require_grad = False

        position = torch.arange(0, num_patches + self.num_tokens).float().unsqueeze(1)
        div_term = (torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model)).exp()

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)
        if torch.cuda.is_available():
            pe = pe.cuda()
        self.register_buffer('pe', pe)

    def __call__(self):
        return self.pe


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        # NOTE scale factor was wrong in my original version, can set manually to be compat with prev weights
        self.scale = qk_scale or head_dim ** -0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]   # make torchscript happy (cannot use tensor as tuple)

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x


def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).

    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.

    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


class Block(nn.Module):

    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)
        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

    def forward(self, x):
        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


class MaskedAutoencoderViT(nn.Module):
    """ Masked Autoencoder with VisionTransformer backbone
    """

    def __init__(self,
                 # node2vec,
                 # time2vec,
                 # moving_average_decay,
                 # beta,
                 # projection_size,
                 # projection_hidden_size,
                 # prediction_hidden_size,
                 # prediction_size,
                 num_tokens,
                 num_time_tokens=1440,
                 num_patches=100, in_chans=3,
                 embed_dim=1024, depth=24, num_heads=16,
                 decoder_embed_dim=512, decoder_depth=8, decoder_num_heads=16,
                 mlp_ratio=4., embed_layer=PatchEmbed, norm_layer=partial(nn.LayerNorm, eps=1e-6), norm_pix_loss=False):
        super().__init__()

        # --------------------------------------------------------------------------
        # MAE encoder specifics
        # self.patch_embed = embed_layer(node2vec=node2vec, time2vec=time2vec, embed_dim=128, dropout=0.)
        self.patch_embed = embed_layer(num_tokens + 1, num_time_tokens, embed_dim)

        # self.patch_embed = PatchEmbed(img_size, patch_size, in_chans, embed_dim)
        num_patches = num_patches
        self.num_classes = 3

        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(torch.zeros(1, num_patches + 1, embed_dim),
                                      requires_grad=False)  # fixed sin-cos embedding

        self.blocks = nn.ModuleList([
            Block(embed_dim, num_heads, mlp_ratio, qkv_bias=True, qk_scale=None, norm_layer=norm_layer)
            for i in range(depth)])
        self.norm = norm_layer(embed_dim)
        # --------------------------------------------------------------------------

        # --------------------------------------------------------------------------
        # MAE decoder specifics
        self.decoder_embed = nn.Linear(embed_dim, decoder_embed_dim, bias=True)

        self.mask_token = nn.Parameter(torch.zeros(1, 1, decoder_embed_dim))

        self.decoder_pos_embed = nn.Parameter(torch.zeros(1, num_patches + 1, decoder_embed_dim),
                                              requires_grad=False)  # fixed sin-cos embedding

        self.decoder_blocks = nn.ModuleList([
            Block(decoder_embed_dim, decoder_num_heads, mlp_ratio, qkv_bias=True, qk_scale=None, norm_layer=norm_layer)
            for i in range(decoder_depth)])

        self.decoder_norm = norm_layer(decoder_embed_dim)
        # self.decoder_pred = nn.Linear(decoder_embed_dim, patch_size**2 * in_chans, bias=True) # decoder to patch
        # --------------------------------------------------------------------------

        self.relation_head = torch.nn.Sequential(
            torch.nn.Linear(128 * 2, 128),  ###change 2 to 4
            torch.nn.BatchNorm1d(128),
            torch.nn.LeakyReLU(),
            torch.nn.Linear(128, 1))
        self.norm_pix_loss = norm_pix_loss
        self.criterion_bce = nn.BCEWithLogitsLoss()
        self.criterion_cls = nn.CrossEntropyLoss()

        self.clstoken = nn.Linear(128 * 2, 3)
        self.acf = nn.ReLU()

        self.apply(self._init_vit_weights)

    def _init_vit_weights(self, module):
        """ ViT weight initialization
        """
        if isinstance(module, nn.Linear):
            if module.out_features == self.num_classes:
                nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)
            else:
                trunc_normal_(module.weight, std=.02)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)
        elif isinstance(module, (nn.LayerNorm, nn.GroupNorm, nn.BatchNorm2d)):
            nn.init.zeros_(module.bias)
            nn.init.ones_(module.weight)

    def random_masking(self, x, mask_ratio):
        """
        Perform per-sample random masking by per-sample shuffling.
        Per-sample shuffling is done by argsort random noise.
        x: [N, L, D], sequence
        """
        N, L, D = x.shape  # batch, length, dim
        len_keep = int(L * (1 - mask_ratio))

        noise = torch.rand(N, L, device=x.device)  # noise in [0, 1]

        # sort noise for each sample
        ids_shuffle = torch.argsort(noise, dim=1)  # ascend: small is keep, large is remove
        ids_restore = torch.argsort(ids_shuffle, dim=1)

        # keep the first subset
        ids_keep = ids_shuffle[:, :len_keep]
        x_masked = torch.gather(x, dim=1, index=ids_keep.unsqueeze(-1).repeat(1, 1, D))

        # generate the binary mask: 0 is keep, 1 is remove
        mask = torch.ones([N, L], device=x.device)
        mask[:, :len_keep] = 0
        # unshuffle to get the binary mask
        mask = torch.gather(mask, dim=1, index=ids_restore)

        return x_masked, mask, ids_restore

    def forward_encoder(self, x, ts, mask_ratio):
        # embed patches
        x, ts_ = self.patch_embed(x, ts)
        xx = x

        # add pos embed w/o cls token
        x = x + self.pos_embed[:, 1:, :]

        # masking: length -> length * mask_ratio
        x, mask, ids_restore = self.random_masking(x, mask_ratio)

        # append cls token
        cls_token = self.cls_token + self.pos_embed[:, :1, :]
        cls_tokens = cls_token.expand(x.shape[0], -1, -1)
        x = torch.cat((cls_tokens, x), dim=1)

        # apply Transformer blocks
        for blk in self.blocks:
            x = blk(x)
        x = self.norm(x)

        return x, mask, ids_restore, xx, ts_

    def forward_decoder(self, x, ids_restore):
        # embed tokens
        x = self.decoder_embed(x)

        # append mask tokens to sequence
        mask_tokens = self.mask_token.repeat(x.shape[0], ids_restore.shape[1] + 1 - x.shape[1], 1)
        x_ = torch.cat([x[:, 1:, :], mask_tokens], dim=1)  # no cls token
        x_ = torch.gather(x_, dim=1, index=ids_restore.unsqueeze(-1).repeat(1, 1, x.shape[2]))  # unshuffle
        x = torch.cat([x[:, :1, :], x_], dim=1)  # append cls token

        # add pos embed
        x = x + self.decoder_pos_embed

        # apply Transformer blocks
        for blk in self.decoder_blocks:
            x = blk(x)
        x = self.decoder_norm(x)

        # predictor projection
        # x = self.decoder_pred(x)

        # remove cls token
        x = x[:, 1:, :]

        return x

    def recovery_loss(self, x, pred, mask):
        """
        imgs: [N, 3, H, W]
        pred: [N, L, p*p*3]
        mask: [N, L], 0 is keep, 1 is remove,
        """
        # target = self.patchify(imgs)
        # if self.norm_pix_loss:
        #     mean = target.mean(dim=-1, keepdim=True)
        #     var = target.var(dim=-1, keepdim=True)
        #     target = (target - mean) / (var + 1.e-6)**.5

        loss = (pred - x) ** 2
        loss = loss.mean(dim=-1)  # [N, L], mean loss per patch

        loss = (loss * mask).sum() / mask.sum()  # mean loss on removed patches
        return loss

    def forward(self, inputs, ts):
        x = self.forward_encoder(inputs, ts, mask_ratio=0)[0]
        return x[:, 0, :]  # CLS token

    def forward_loss(self, intputs, ts, targets, mask_ratio1=0.7, mask_ratio2=0.8):

        latent1, mask1, ids_restore1, xx1, ts1 = self.forward_encoder(intputs, ts, mask_ratio1)
        latent2, mask2, ids_restore2, xx2, ts2 = self.forward_encoder(intputs, ts, mask_ratio2)

        pred1 = self.forward_decoder(latent1, ids_restore1)  # [N, L, p*p*3]
        pred2 = self.forward_decoder(latent2, ids_restore2)  # [N, L, p*p*3]

        cls_token_1 = latent1[:, 0, :]
        cls_token_2 = latent2[:, 0, :]

        # cls_token_rr1 = torch.cat([cls_token_1, torch.squeeze(ts1[:,0,:],1)],1)
        # cls_token_rr2 = torch.cat([cls_token_2, torch.squeeze(ts2[:,0,:],1)],1)
        # #####CLS
        # cls_token_c1 = self.acf(self.clstoken(torch.cat([cls_token_1, torch.squeeze(ts1[:, 0, :], 1)], 1)))
        # cls_token_c2 = self.acf(self.clstoken(torch.cat([cls_token_2, torch.squeeze(ts2[:, 0, :], 1)], 1)))

        ###peak offpeak classification
        # loss_cls1 = self.criterion_cls(torch.squeeze(cls_token_c1, 1), targets)
        # loss_cls2 = self.criterion_cls(torch.squeeze(cls_token_c2, 1), targets)
        # loss_cls = 0.5 * (loss_cls1 + loss_cls2)
        loss_cls = 0.

        ####Rec
        loss_rec1 = self.recovery_loss(xx1, pred1, mask1)
        loss_rec2 = self.recovery_loss(xx2, pred2, mask2)
        loss_rec = 0.5 * (loss_rec1 + loss_rec2)

        #####RR

        cls_feature_rr = torch.cat([cls_token_1, cls_token_2], 0)
        relation_pairs, targets_rr, scores = self.aggregate(cls_feature_rr, K=2)
        if torch.cuda.is_available():
            scores = scores.cuda()
            targets_rr = targets_rr.cuda()
        loss_rr = self.criterion_bce(torch.squeeze(scores, 1), targets_rr)

        return loss_cls, loss_rec, loss_rr, pred1, mask1, pred2, mask2

    def aggregate(self, features, K=2):
        relation_pairs_list = list()
        targets_list = list()
        size = int(features.shape[0] / K)
        shifts_counter = 1
        for index_1 in range(0, size * K, size):
            for index_2 in range(index_1 + size, size * K, size):
                # Using the 'cat' aggregation function by default
                pos_pair = torch.cat([features[index_1:index_1 + size],
                                      features[index_2:index_2 + size]], 1)
                # Shuffle without collisions by rolling the mini-batch (negatives)
                neg_pair = torch.cat([
                    features[index_1:index_1 + size],
                    torch.roll(features[index_2:index_2 + size],
                               shifts=shifts_counter, dims=0)], 1)
                relation_pairs_list.append(pos_pair)
                relation_pairs_list.append(neg_pair)
                targets_list.append(torch.ones(size, dtype=torch.float32))
                targets_list.append(torch.zeros(size, dtype=torch.float32))
                shifts_counter += 1
                if (shifts_counter >= size):
                    shifts_counter = 1  # avoid identity pairs
        relation_pairs = torch.cat(relation_pairs_list, 0)
        targets = torch.cat(targets_list, 0)
        # print(relation_pairs.size())
        return relation_pairs, targets, self.relation_head(relation_pairs)

    def embed(self, intputs, ts, mask_ratio=0.75):
        latent, _, _, _, _ = self.forward_encoder(intputs, ts, mask_ratio)

        return latent[:, 0, :]


class MAERRCD(Encoder):
    def __init__(self, sampler, num_roads, num_time_tokens, road_col, time_col,
                 num_patches, in_chans, embed_dim, depth, num_heads,
                 decoder_embed_dim, decoder_depth, decoder_num_heads):
        super(MAERRCD, self).__init__(sampler, "MAERRCD-d{}-p{}".format(embed_dim, num_patches) +
                                      "-l{}-h{}-de{}-dl{}-dh{}".format(depth, num_heads, decoder_embed_dim, decoder_depth, decoder_num_heads))

        self.road_col = int(road_col)
        self.time_col = int(time_col)
        self.num_patches = num_patches
        self.num_roads = num_roads
        self.output_size = embed_dim

        self.model = MaskedAutoencoderViT(
            num_tokens=num_roads, num_time_tokens=num_time_tokens,
            num_patches=num_patches, in_chans=in_chans, embed_dim=embed_dim, depth=depth, num_heads=num_heads,
            decoder_embed_dim=decoder_embed_dim, decoder_depth=decoder_depth, decoder_num_heads=decoder_num_heads)

    def _organize_models_and_data(self, trip, valid_len):
        B, L, E_in = trip.shape

        src_mask = repeat(torch.arange(end=L, device=trip.device),
                          'L -> B L', B=B) >= repeat(valid_len, 'B -> B L', L=L)  # (B, L)
        x, src_mask = self.sampler(trip, src_mask)

        masked_values = torch.zeros_like(x)
        masked_values[..., self.road_col] = self.num_roads
        x = torch.where(src_mask.unsqueeze(-1), masked_values, x)

        if L < self.num_patches:
            x = torch.cat([x, repeat(x[:, -1, :], 'B E -> B L E', L=self.num_patches - L)], dim=1)
        elif L > self.num_patches:
            print("Truncating trip to length {}".format(self.num_patches))
            x = x[:, :self.num_patches, :]

        x[..., self.time_col] = (x[..., self.time_col] / 60) % 1440

        return x

    def forward(self, trip, valid_len):
        x = self._organize_models_and_data(trip, valid_len)

        return self.model(x[..., self.road_col].long(), x[..., self.time_col].long())

    def forward_loss(self, trip, valid_len, mask_ratio1=0.7, mask_ratio2=0.8):
        x = self._organize_models_and_data(trip, valid_len)

        return self.model.forward_loss(x[..., self.road_col].long(), x[..., self.time_col].long(), None, mask_ratio1, mask_ratio2)
